auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: happyze biog
url: http://www.happyze.tk
feed: /atom.xml
author_info: <a href="http://happyze.github.io">happyze</a>
