auto: true

markdown: kramdown
kramdown:
    input: GFM
rouge: true
permalink: /:title

title: happyze blog
url: http://happyze.github.io
feed: /atom.xml
author_info: <a href="http://happyze.github.io">happyze</a>
